export default [
  {
    id: "26789",
    with: 375,
    height: 499,
    canvasBg: "#fff",
    imgUrl: require("../assets/templates/mz-img.png"),
    components: [
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/mz-bg.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 375,
          top: 0,
          left: 0,
        },
        events: {},
        uuid: "img--a74c1fe1-2c9f-4aec-bcdc-08e4d3ab5830",
      },
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/mz-name.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 88,
          top: 19,
          left: 142,
        },
        events: {},
        uuid: "img--fcc48f06-6f61-49b3-97e8-69d38872de71",
      },
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/mz-2.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 92,
          top: 24,
          left: 14,
        },
        events: {},
        uuid: "img--0c30a936-f52d-4468-a164-8566e5eac20f",
      },
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/mz-1.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 30,
          top: 24,
          left: 323,
        },
        events: {},
        uuid: "img--db197b81-cd8f-4ce6-bef2-3a6a153d5492",
      },
    ],
  },
  {
    id: "5201314",
    with: 375,
    height: 499,
    canvasBg: "#fff",
    imgUrl: require("../assets/templates/520-img.png"),
    components: [
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/520-bg.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 375,
          height: 499,
          top: 0,
          left: 0,
        },
        events: {},
        uuid: "img--ef6d67dc-392c-49f0-9fb8-d6332c02b7c4",
      },
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/520-lovers.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 180,
          top: 271,
          left: 61,
        },
        events: {},
        uuid: "img--11101cbd-86ee-479e-8567-4c156aca71fb",
      },
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/520-heart.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 375,
          top: 0,
          left: 0,
        },
        events: {},
        uuid: "img--cca8a7d5-fc16-4581-9316-ca900d319548",
      },
      {
        key: "img",
        template: "custom-img",
        title: "图片",
        icon: "icon-tupian",
        attr: {
          imgUrl: require("../assets/templates/520-text.png"),
          blur: 0,
          brightness: 100,
          contrast: 100,
          grayscale: 0,
          hueRotate: 0,
          invert: 0,
          opacity: 100,
          saturate: 100,
          sepia: 0,
          dropShadow: "0px 0px 0px rgba(0, 0, 0, 0)",
        },
        style: {
          width: 201,
          top: 224,
          left: 86,
        },
        events: {},
        uuid: "img--29e32810-4794-476e-af99-189a341154b4",
      },
    ],
  },
] as any;
